const Json = [
  {
    id: "1",
    name: "New 1-bedroom mountain guesthouse",
    description:
      "Perfect for both ski weekends and quiet self-care retreats, this modern 400-square-foot guesthouse is nestled in 10 acres of forest across the street from Devil's Thumb Ranch (20 minutes to the lodge), 5 mi. from Fraser, and 15 mi. from Winter Park Resort.\n\nGuesthouse includes a king-size bed and kitchenette with everything you need to cook.\n\nThings to know:\n\n—Ample parking\n—We live in the main house with our two dogs and are on site\n—4WD drive likely a must in the winter",
    host: "Tasha",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "185",
    cleaning_price: "75",
    property_type: "Guesthouse",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "North America",
    Region2: "United States",
    country: "United States",
    state: "Colorado",
    city_id: "Fraser",
    category: "National parks",
    extra_benefits1: "Self check-in",
    extra_benefits_description: "",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Mountain view",
    amenity2: "Dedicated workspace",
    amenity3: "TV",
    amenity4: "Free dryer",
    amenity5: "Hairy dryer",
    amenity6: "Wifi",
    amenity7: "Free parking on premises",
    amenity8: "Free washer",
    amenity9: "Private backyard",
    amenity10: "Refrigerator",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "2",
    name: "NordseeEstate - Private Nordsee Hideaway",
    description:
      "NordseeEstate is the entire house: NordseeLounge, NordseeLoft and NordseeLodge",
    host: "Nicola Und Christoph",
    number_bedrooms: "8",
    number_bathrooms: "3",
    number_beds: "8",
    address: "unsure",
    price: "543",
    cleaning_price: "411",
    property_type: "Apartment",
    room_type: "Shared room",
    language1: "English",
    language2: "German",
    Region1: "Europe",
    Region2: "",
    country: "Germany",
    state: "Schleswig-Holstein",
    city_id: "Tetenbull",
    category: "National parks",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "Check yourself in with the lockbox.",
    extra_benefits3: "Superhost",
    extra_benefits3_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    amenity1: "Garden view",
    amenity2: "Waterfront",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "Park view",
    amenity7: "Kitchen",
    amenity8: "Dedicated workspace",
    amenity9: "Private sauna",
    amenity10: "TV",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "3",
    name: "Aux d'Estaing Croisés, Gîte accessible à tous",
    description:
      "At Estaing Croisée, this is our family's project, animated by the deep desire to offer holiday stays and activities for all and especially to people with disabilities.\nThe charm of the mountain, an atypical but accessible place, ethical and many ideas...\nEmbark on this human adventure with us!",
    host: "Emilie",
    number_bedrooms: "2",
    number_bathrooms: "1",
    number_beds: "3",
    address: "unsure",
    price: "76",
    cleaning_price: "54",
    property_type: "House",
    room_type: "Shared room",
    language1: "English",
    language2: "France",
    Region1: "Europe",
    Region2: "",
    country: "France",
    state: "",
    city_id: "Estaing",
    category: "National parks",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "Great check-in experience",
    extra_benefits3_description:
      "100% of recent guests gave the check-in process a 5-star rating",
    amenity1: "Courtyard view",
    amenity2: "Waterfront",
    amenity3: "Free parking on premises",
    amenity4: "TV",
    amenity5: "Free washer",
    amenity6: "Dedicated workspace",
    amenity7: "Pets allowed",
    amenity8: "Kitchen",
    amenity9: "Garden view",
    amenity10: "Wifi",
    accessibility1: "Step-free guest entrance",
    accessibility2: "Guest entrance wider than 32 inches",
    accessibility3: "Accessible parking spot",
    accessibility4: "Step-free bedroom access",
    accessibility5: "Bedroom entrance wider than 32 inches",
    accessibility6: "Step-free bathroom access",
    accessibility7: "Step-free access to the bathrooms",
    accessibility8: "Bathroom entrance wider than 32 inches",
    accessibility9: "Shower grab bar",
    accessibility10: "Toilet grab bar",
    "": "Shower or bath chair",
  },
  {
    id: "4",
    name: "VILLA ARCOIRIS - WHERE COLORS SHINE - ROOM 1",
    description:
      "Private cabin, independent entrance, air-conditioned, spacious, modern, comfortable, restaurant service, organic dinner. Laundry service, private taxis, specialized hiking with English-speaking guide.\nWe have enough space for parking bicycles, motorcycles and cars",
    host: "Maria De",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "14",
    cleaning_price: "0",
    property_type: "House",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "",
    country: "Cuba",
    state: "",
    city_id: "CU",
    category: "National parks",
    extra_benefits1: "Great check-in experience",
    extra_benefits_description:
      "100% of recent guests gave the check-in process a 5-star rating.",
    extra_benefits2: "Park for free",
    extra_benefits2_description:
      "This is one of the few places in the area with free parking.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "TV",
    amenity3: "Dryer",
    amenity4: "Washer",
    amenity5: "Free parking on premises",
    amenity6: "Air conditioning",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "5",
    name: "Cabaña María Luisa 4",
    description:
      "Come enjoy nature  and create unforgettable memories surrounded by your family",
    host: "Ramon",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "116",
    cleaning_price: "0",
    property_type: "House",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "",
    city_id: "Santiago",
    category: "National parks",
    extra_benefits1: "Self check-in",
    extra_benefits_description: "Check yourself in with the lockbox.",
    extra_benefits2: "Superhost",
    extra_benefits2_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "TV",
    amenity3: "Dryer",
    amenity4: "Washer",
    amenity5: "Free parking on premises",
    amenity6: "Air conditioning",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "6",
    name: "Rm6 - Accessible Jungle Studio A/C,/TV/Kitchenette",
    description:
      "We both like meeting interesting people for conversation and making new friends.  Come and enjoy our beautiful Guesthouse in Tropical Paradise.  We're located close to everything in Manuel Antonio, with easy access to local public bus service outside our gate, we also have parking for your rental car.  Our house is spotlessly clean and our Tropical gardens are lovingly maintained. ",
    host: "Mike",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "175",
    cleaning_price: "50",
    property_type: "House",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "Costa Rica",
    country: "Costa Rica",
    state: "",
    city_id: "Manuel Antonio",
    category: "National parks",
    extra_benefits1: "Dedicated worksapce",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Dive right in",
    extra_benefits2_description:
      "This is one of the few places in the area with a pool.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Wifi",
    amenity3: "Free parking on premises",
    amenity4: "Dedicated workspace",
    amenity5: "",
    amenity6: "",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "Step-free guest entrance",
    accessibility2: "Guest entrance wider than 32 inches",
    accessibility3: "Accessible parking spot",
    accessibility4: "Step-free bedroom access",
    accessibility5: "Bedroom entrance wider than 32 inches",
    accessibility6: "Step-free bathroom access",
    accessibility7: "Step-free access to the bathrooms",
    accessibility8: "Bathroom entrance wider than 32 inches",
    accessibility9: "Shower grab bar",
    accessibility10: "Toilet grab bar",
    "": "Shower or bath chair",
  },
  {
    id: "7",
    name: "Hotel México en la Piel (Casa Tamaulipas)",
    description: "Casa Tamaulipas",
    host: "México En La Piel",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "185",
    cleaning_price: "0",
    property_type: "Hotel",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "",
    city_id: "Baja California",
    category: "National parks",
    extra_benefits1: "Self check-in",
    extra_benefits_description: "You can check in with the doorman",
    extra_benefits2: "Superhost",
    extra_benefits2_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Wifi",
    amenity2: "TV",
    amenity3: "Free parking on premises",
    amenity4: "Backyard",
    amenity5: "Patio or balcony",
    amenity6: "Air conditioning",
    amenity7: "Indoor fireplace",
    amenity8: "Breakfast",
    amenity9: "Long term stays allowed",
    amenity10: "Hair dryer",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "8",
    name: "Propiedad Completa 25 huéspedes cerca a Tolantongo",
    description:
      "It rents full property that can comfortably accommodate up to 20 people. There are 3 apartments in total,  6 rooms, 9 beds, 1 sofa bed, 4 smart TVs, solar heater,  internet, 2 full bathrooms , 5 half bathrooms,  1 full kitchen, 1 kitchenette, 3 ovens, 2 refrigerators, coffee makers and 1 washing machine.\nRoofed indoor parking for several cars, just 35 minutes from Las Grotte de Tolantongo and right in the center of Cardonal, Hidalgo.",
    host: "Samuel",
    number_bedrooms: "7",
    number_bathrooms: "5",
    number_beds: "12",
    address: "unsure",
    price: "210",
    cleaning_price: "26",
    property_type: "Apartment",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "",
    city_id: "Cardonal",
    category: "National parks",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "You can check in with the doorman",
    extra_benefits3: "Superhost",
    extra_benefits3_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    amenity1: "Kitchen",
    amenity2: "Dedicated workspace",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "TV",
    amenity7: "Washer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "9",
    name: "Private 1700's Mansion House with an english park",
    description:
      "A very own 1700's mansion with English park. Right next to a nice beach (800 meters), access to a small private boat with its own jetty, barbecue, soccer goals, 6 pcs free bicycles, sauna. Lake Vätterns offers great fishing, kayak routes, excursions, hiking trails, etc. Mansion is close to family-friendly activities. You'll love my place. ",
    host: "Johan",
    number_bedrooms: "8",
    number_bathrooms: "2.5",
    number_beds: "12",
    address: "unsure",
    price: "820",
    cleaning_price: "174",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Swedish",
    Region1: "Europe",
    Region2: "",
    country: "Sweden",
    state: "",
    city_id: "Aspa Bruk",
    category: "Mansions",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "Check yourself in with the lockbox.",
    extra_benefits3: "Superhost",
    extra_benefits3_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    amenity1: "Courtyard view",
    amenity2: "Garden view",
    amenity3: "Kitchen",
    amenity4: "Dedicated workspace",
    amenity5: "Wifi",
    amenity6: "Pets allowed",
    amenity7: "Free parking on premises",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "10",
    name: "Timeless elegance",
    description:
      "Pool, WiFi, the entire place at your private disposal. You can't imagine that a piece of Heaven it's on the heart. You will understand it as you'll cross the gate of our villa! Peace, serenity, relax. You'll breathe Love in all nooks of this authentic Tuscan property entirely at your exclusive disposalA real manor house tastefully furnished according to the authentic Tuscan Tradition of the Past.",
    host: "Luca",
    number_bedrooms: "8",
    number_bathrooms: "5.5",
    number_beds: "9",
    address: "unsure",
    price: "756",
    cleaning_price: "195",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "",
    city_id: "Poggibonsi",
    category: "Mansions",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Private pool",
    amenity2: "Courtyard view",
    amenity3: "Garden view",
    amenity4: "Kitchen",
    amenity5: "Dedicated workspace",
    amenity6: "Wifi",
    amenity7: "Pets allowed",
    amenity8: "Free parking on premises",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "11",
    name: "Castello di Galbino",
    description:
      "Galbino is a stunning 16th century castle in the midst of nature just a few kilometres from the enchanting village of Anghiari.\nOn a hill surrounded by woods and fields, Galbino Castle is a private and exclusive place to relax, explore nature, visit the cultural attractions of the area and enjoy the Tuscan delights of food and wine. ",
    host: "Stefano",
    number_bedrooms: "10",
    number_bathrooms: "8.5",
    number_beds: "15",
    address: "unsure",
    price: "1308",
    cleaning_price: "378",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "",
    city_id: "Anghiari",
    category: "Castles",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Dedicated workspace",
    amenity3: "Private pool",
    amenity4: "Wifi",
    amenity5: "Free parking on premises",
    amenity6: "Pets allowed",
    amenity7: "TV",
    amenity8: "Washer",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "12",
    name: "The small castle of the Moors II,access to the sea",
    description:
      "Holiday Home in Municipality of Ravello,  Regional License Code :\n15065104EXT0209.\nA spacious terrace (all for exclusive use) with sun loungers, outdoor shower, barbecue, lift, parking, private access to the sea, air-conditioned rooms, a large and bright living room, unique architecture and proximity to the center of the town of Minori ( 500 meters), are the strengths of this apartment, ",
    host: "Francesecopaolo",
    number_bedrooms: "2",
    number_bathrooms: "2.5",
    number_beds: "2",
    address: "unsure",
    price: "292",
    cleaning_price: "130",
    property_type: "House",
    room_type: "Shared room",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "",
    city_id: "Ravello",
    category: "Castles",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "TV",
    amenity4: "Washer",
    amenity5: "Free parking on premises",
    amenity6: "Private pool",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "13",
    name: "VILLA TORNO-Lake Como view & pool",
    description:
      "The first feeling you have arriving at Villa Torno  is the strong energy emanating from a wild and uncontaminated place. Landscape and Nature do the rest: the rock cavity in the basement and the breathtaking views towards the lake.\nBe ready to enjoy and relax in our unique pool among the quarry rocks.",
    host: "Erika",
    number_bedrooms: "4",
    number_bathrooms: "4.5",
    number_beds: "4",
    address: "unsure",
    price: "2379",
    cleaning_price: "487",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "",
    city_id: "Torno",
    category: "Caves",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "You can check in with the doorman",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Mountain view",
    amenity2: "Kitchen",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "Private pool",
    amenity6: "",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "14",
    name: "Case degli Avi, esperienza abitativa in grotta",
    description:
      'Cave houses.\nThe Casa degli Avi ,in line with the "return to origin" trend,  is  a project focused on the ethnographic preservation of the ancient habitat and the recovery and enhancement of the identity of the places. ',
    host: "Giovanni",
    number_bedrooms: "4",
    number_bathrooms: "4",
    number_beds: "5",
    address: "unsure",
    price: "78",
    cleaning_price: "16",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "",
    city_id: "MODICA",
    category: "Caves",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Courtyard view",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "TV",
    amenity6: "Dedicated workspace",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "15",
    name: "Cocon Nocturne ★PISCINE★JARDIN★NETFLIX★PARKING",
    description:
      "“the NIGHT COCOON” - 5 \n\n ★★★★★ All the comforts for a pleasant stay, whether for a few days of relaxation or for your business trips.\n\nTo protect you, all surfaces but also the laundry are disinfected after each stay.",
    host: "Frederic",
    number_bedrooms: "1",
    number_bathrooms: "1.5",
    number_beds: "2",
    address: "unsure",
    price: "114",
    cleaning_price: "43",
    property_type: "Apartment",
    room_type: "Entire place",
    language1: "English",
    language2: "French",
    Region1: "Europe",
    Region2: "",
    country: "France",
    state: "Grand Est",
    city_id: "Macheren",
    category: "Amazing pools",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "Check yourself in with the lockbox.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Kitchen",
    amenity3: "Dedicated worksapce",
    amenity4: "Wifi",
    amenity5: "Private pool",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "TV",
    amenity9: "Free parking on premises",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "16",
    name: "Breakfast included Luxury condo with swimming pool",
    description:
      "This special place is close to everything, making it easy to plan your visit. Very safe and luxury, you can enjoy SPA and also all the restaurants by the river.",
    host: "Lulia",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "198",
    cleaning_price: "248",
    property_type: "Apartment",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "United Kingdom",
    Region2: "Europe",
    country: "United Kingdom",
    state: "",
    city_id: "London",
    category: "Amazing pools",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Private pool",
    amenity4: "Pets allowed",
    amenity5: "TV",
    amenity6: "Washer",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "17",
    name: "The Luxury Condo at Reserva Conchal, Great Beach",
    description:
      "Beautiful overlooking the Pacific Ocean contemporary 2 bedrooms apartment with privet terrace, separate air conditioning in each room, stainless steal kitchen appliances and fully equipped private Landry room. Free excess to the State-of-the-art Beach Club. Fitness Center. Tennis court. The spa by Westin. The free shuttle from club to condo. Audubon-certified Robert Trent Jones II award-winning 18 hole golf course. Wildlife Refuge and miles of natural trails for biking and hiking. 24/7 security.",
    host: "Yelena",
    number_bedrooms: "2",
    number_bathrooms: "2",
    number_beds: "2",
    address: "unsure",
    price: "300",
    cleaning_price: "0",
    property_type: "Apartment",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "",
    country: "Costa Rica",
    state: "",
    city_id: "Liberia",
    category: "Amazing views",
    extra_benefits1: "Free cancellation for 48 hours",
    extra_benefits_description: "",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Private pool",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "TV",
    amenity7: "Washer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "18",
    name: "Diamante del Sol 10-2S - Family Friendly Penthouse",
    description:
      "Masterfully designed luxurious 4 bedroom, 5 bath penthouse. Elegantly furnished, the unit comfortably host groups of up to 12 guests. A great fit for families and groups looking to vacation together.",
    host: "Come To",
    number_bedrooms: "4",
    number_bathrooms: "5",
    number_beds: "6",
    address: "unsure",
    price: "795",
    cleaning_price: "300",
    property_type: "Apartment",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "",
    country: "Costa Rica",
    state: "",
    city_id: "Jaco",
    category: "Amazing views",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Free parking on premises",
    amenity4: "Private pool",
    amenity5: "TV",
    amenity6: "Dryer",
    amenity7: "Washer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "19",
    name: "Stunning, Modern Ground Floor Seaview Apartment",
    description:
      "Self-contained ground floor apartment situated on the beautiful front of Lytham St. Anne's. Consisting of a super king size master bedroom, a double bedroom and a sofa bed, with the ability to sleep up to 6 people and two well behaved dogs. Private hot tub. Free wifi (speeds up to 65Mbps). Free off-road parking spaces available. Ideal property for a family getaway or for business purposes. ",
    host: "Nikki",
    number_bedrooms: "2",
    number_bathrooms: "1",
    number_beds: "3",
    address: "unsure",
    price: "248",
    cleaning_price: "0",
    property_type: "Apartment",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "United Kingdom",
    Region2: "Europe",
    country: "United Kingdom",
    state: "",
    city_id: "Lancashire",
    category: "Golfing",
    extra_benefits1: "Self check-in",
    extra_benefits_description: "Check yourself in with the lockbox.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Free parking on premises",
    amenity3: "Pets allowed",
    amenity4: "Washer",
    amenity5: "TV",
    amenity6: "Hair Dryer",
    amenity7: "Wifi",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "20",
    name: "lit dans studio calme, tout équipé a partage",
    description:
      "Bed in a 20 m2 studio, fully equipped, close to the center, nearby public transport, free parking.",
    host: "Bogdan",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "30",
    cleaning_price: "0",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "French",
    Region1: "Europe",
    Region2: "",
    country: "France",
    state: "",
    city_id: "Garches",
    category: "Golfing",
    extra_benefits1: "Great for remote work",
    extra_benefits_description:
      "Fast wifi at 329 Mbps, plus a dedicated workspace in a common area.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Dedicated worksapce",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "21",
    name: "Stay with MUSIC ARTIST in 1BHK Home (*FREE WiFi)!",
    description:
      "Comfortable 1BHK home / music studio with free WiFi and access to most amenities and facilities, I live here and LIVING ROOM BEDS are provided on to guests, as per time, schedule, and your comfort. Check listing type when booking : Stay is provided either as a Private Room or a Shared Room type, as per availability.",
    host: "Ronak",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "10",
    cleaning_price: "0",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Hindi",
    Region1: "Asia",
    Region2: "",
    country: "India",
    state: "Gujarat",
    city_id: "Ahmedabad",
    category: "Creative spaces",
    extra_benefits1: "Great for remote work",
    extra_benefits_description:
      "Fast wifi at 329 Mbps, plus a dedicated workspace in a common area.",
    extra_benefits2: "Superhost",
    extra_benefits2_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Kitchen",
    amenity3: "Dedicated worksapce",
    amenity4: "Wifi",
    amenity5: "Free parking on premises",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "TV",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "22",
    name: "Thoroughly disinfected room /bath Pty City Mansion",
    description:
      "Do you want to discover Panamanian culture? Is your dream to travel around the world without spending too much money in a quiet tranquil place, with lots of privacy and rainforest views? Come to fully enjoy the effervescence of Panama City, the home of more than 2 million people, finding accommodation in a family house, situated in the city’s safest area",
    host: "Stephanie",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "19",
    cleaning_price: "20",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "",
    country: "Panama",
    state: "",
    city_id: "Panama",
    category: "Creative spaces",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "You can check in with the doorman",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Dedicated worksapce",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "Garden view",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "23",
    name: "B & B.POWIS COTTAGE COTTAGE,LAUGHARNE.",
    description:
      "Situated in an elevate position overlooking Carmarthen bay with panoramic views\nThere are two double rooms a sea view and a balcony for those lovely sunny morning breakfasts\n\nThe space\nAvailable two double rooms with sea views and balcony for guest to enjoy the panoramic vista of Carmarthen Bay.",
    host: "Kaye",
    number_bedrooms: "2",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "105",
    cleaning_price: "12",
    property_type: "Hotel",
    room_type: "Private room",
    language1: "English",
    language2: "",
    Region1: "United Kingdom",
    Region2: "Europe",
    country: "United Kingdom",
    state: "",
    city_id: "Laugharne",
    category: "Off-the-grid",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Wifi",
    amenity2: "Free parking on premises",
    amenity3: "TV",
    amenity4: "Dryer",
    amenity5: "Hairy dryer",
    amenity6: "Breakfast",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "24",
    name: "The Willow Room at Four Oaks",
    description:
      "Luxury en-suite B&B. Rural glen location, only 10 mins to Oban town centre, 12 mins to ferry terminal. Wi-Fi. Free parking. EV car charging. Rooms are in a self-contained annexe with sitting room and outside deck area for panoramic views to Ben Cruachan.",
    host: "Duncan",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "129",
    cleaning_price: "0",
    property_type: "Hotel",
    room_type: "Private room",
    language1: "English",
    language2: "",
    Region1: "United Kingdom",
    Region2: "Europe",
    country: "United Kingdom",
    state: "Scotland",
    city_id: "Glencruitten",
    category: "Off-the-grid",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Mountain view",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "TV",
    amenity6: "Patio or balcony",
    amenity7: "Dryer",
    amenity8: "Washer",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "25",
    name: "Hotel AFRICAM SAFARI. Natural Suites hotel oasis",
    description:
      "Hotel located 5 min from AFRICAM SAFARI in the middle of nature. \nAt night with a little luck you can hear the Lions of Africam roar. We are also the only hotel in the area, with all the amenities such as towels, soap and hotel amenities. We also have an exclusive exit to Lake Valsequillo, where you could enjoy a boat ride.",
    host: "Mireya",
    number_bedrooms: "2",
    number_bathrooms: "1",
    number_beds: "6",
    address: "unsure",
    price: "147",
    cleaning_price: "0",
    property_type: "Hotel",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "Puebla",
    city_id: "Heroica Puebla de Zaragoza",
    category: "Lakefront",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Kitchen",
    amenity3: "Dedicated worksapce",
    amenity4: "Wifi",
    amenity5: "Free parking on premises",
    amenity6: "Private pool",
    amenity7: "Pets allowed",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "26",
    name: "Tequesquitengo acceso al lago, 8 px pool & jacuzzi",
    description:
      "Enjoy the attractions that the Tequesquitengo lagoon has.\n\nIf you wish to purchase this accommodation through cash payment, you will receive a special discount, call us to find out more about this service: Mexico (+52) 5529612166.",
    host: "Active Viajes",
    number_bedrooms: "2",
    number_bathrooms: "2",
    number_beds: "3",
    address: "unsure",
    price: "48",
    cleaning_price: "26",
    property_type: "Apartment",
    room_type: "Private room",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "Morelos",
    city_id: "Tequesquitengo",
    category: "Lakefront",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Dedicated workspace",
    extra_benefits2_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Wifi",
    amenity3: "Kitchen",
    amenity4: "Dedicated worksapce",
    amenity5: "Free parking on premises",
    amenity6: "",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "27",
    name: "*The Hideaway: Authentic Cotswolds Village Living*",
    description:
      "Nestled in an area of outstanding beauty, the hideaway offers a peaceful stay within a 10 minute drive from Cheltenham, famous for the races and various festivals throughout the year. ",
    host: "Irene",
    number_bedrooms: "2",
    number_bathrooms: "1",
    number_beds: "2",
    address: "unsure",
    price: "235",
    cleaning_price: "80",
    property_type: "Guesthouse",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "United Kingdom",
    Region2: "Europe",
    country: "United Kingdom",
    state: "England",
    city_id: "Birdlip",
    category: "Design",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Dedicated workspace",
    extra_benefits2_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits3: "Self check-in",
    extra_benefits3_description: "Check yourself in with the lockbox. ",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Dedicated worksapce",
    amenity4: "Free parking on premises",
    amenity5: "TV",
    amenity6: "Washer",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "28",
    name: "Oceanfront Romantic Suite Santiago in Las Catalinas",
    description:
      "Slide open a wall of tall blue doors of Suite Santiago and step barefoot onto the breezy bougainvillea-draped veranda where an alfresco Costa Rican breakfast (included with booking) is served to the background music of the surf. Amble 4 doors down a cobblestone street to the pools of Beach Club or wander the nature path to the Pacific Ocean, a stone throw's away. ",
    host: "Nancy",
    number_bedrooms: "2",
    number_bathrooms: "2",
    number_beds: "5",
    address: "unsure",
    price: "725",
    cleaning_price: "0",
    property_type: "Guesthouse",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "",
    country: "Costa Rica",
    state: "Guanacaste Province",
    city_id: "Danta Beach",
    category: "Design",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Dedicated worksapce",
    amenity4: "Free parking on premises",
    amenity5: "TV",
    amenity6: "Washer",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "29",
    name: "The Treehouse Game and Stay",
    description:
      "The Treehouse Game and Stay isn't your usual self catering apartment.  It has its own pool table and retro arcade machine exclusively for your use.  Situated above our oak framed cartlodge in the grounds of our house on the edge of the 44 acre village green of Old Buckenham.  The village has 2 pubs, shop and country walks.",
    host: "Jeremy",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "123",
    cleaning_price: "0",
    property_type: "Guesthouse",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "United Kingdom",
    Region2: "Europe",
    country: "United Kingdom",
    state: "England",
    city_id: "Old Buckenham",
    category: "Play",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "Check yourself in with the lockbox.",
    extra_benefits3: "Free cancellation for 48 hours",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Free parking on premises",
    amenity4: "TV",
    amenity5: "Hairy dryer",
    amenity6: "",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "30",
    name: "Generator - Bed in female Dorm",
    description:
      "This room is girls only.\n\n- Private bathroom\n- All bunks include a light feature, personal shelf, charging station with USB port, and under-bed lockers\n- Pillow, duvet, linen all supplied",
    host: "Generator",
    number_bedrooms: "1",
    number_bathrooms: "1",
    number_beds: "1",
    address: "unsure",
    price: "22",
    cleaning_price: "0",
    property_type: "Hotel",
    room_type: "Shared room",
    language1: "English",
    language2: "Danish",
    Region1: "Europe",
    Region2: "",
    country: "Denmark",
    state: "",
    city_id: "Copenhagen",
    category: "Play",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Wifi",
    amenity2: "Washer",
    amenity3: "Hair dryer",
    amenity4: "",
    amenity5: "",
    amenity6: "",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "31",
    name: "Casali con piscina in condivisione - 18 persone",
    description:
      "Small local stone farmhouses, with original beams, located in a complex of 9 accommodations, with garden and swimming pool in common use. The number of rooms and bathrooms allocated varies according to the number of guests. The photos are indicative. Each farmhouse is equipped with sofa beds, for up to 4 people in the two-room apartments and 6 people in the three-room apartments.",
    host: "Gertrude",
    number_bedrooms: "5",
    number_bathrooms: "3",
    number_beds: "9",
    address: "unsure",
    price: "314",
    cleaning_price: "0",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "Umbria",
    city_id: "Ospedalicchio",
    category: "Adapted",
    extra_benefits1: "Great location",
    extra_benefits_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Garden view",
    amenity2: "Kitchen",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "Private pool",
    amenity6: "TV",
    amenity7: "Pets allowed",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "Step-free guest entrance",
    accessibility2: "Guest entrance wider than 32 inches",
    accessibility3: "Accessible parking spot",
    accessibility4: "Step-free bedroom access",
    accessibility5: "Bedroom entrance wider than 32 inches",
    accessibility6: "Step-free bathroom access",
    accessibility7: "Step-free access to the bathrooms",
    accessibility8: "Bathroom entrance wider than 32 inches",
    accessibility9: "Shower grab bar",
    accessibility10: "Toilet grab bar",
    "": "Shower or bath chair",
  },
  {
    id: "32",
    name: "Beach front apartment in Acapulco!",
    description:
      "Hi there!\nI´m Adriana and I have an amazing apartment in Acapulco Diamante right in front of the beach! Includes all amenities such as a jacuzzi, swimming pool, access to the Mayan Palace 18 hole golf course, spa and La Isla shopping Mall. \nThe place is a dream come true.",
    host: "Adriana",
    number_bedrooms: "4",
    number_bathrooms: "3",
    number_beds: "8",
    address: "unsure",
    price: "236",
    cleaning_price: "98",
    property_type: "Apartment",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "Guerrero",
    city_id: "Acapulco",
    category: "Adapted",
    extra_benefits1: "Dedicated worksapce",
    extra_benefits_description:
      "A private room with wifi that’s well-suited for working.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "You can check in with the doorman",
    extra_benefits3: "Free cancellation for 48 hours",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Dedicated workspace",
    amenity4: "Free parking on premises",
    amenity5: "Private pool",
    amenity6: "",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "Step-free guest entrance",
    accessibility2: "Guest entrance wider than 32 inches",
    accessibility3: "Accessible parking spot",
    accessibility4: "Step-free bedroom access",
    accessibility5: "Bedroom entrance wider than 32 inches",
    accessibility6: "Step-free bathroom access",
    accessibility7: "Step-free access to the bathrooms",
    accessibility8: "Bathroom entrance wider than 32 inches",
    accessibility9: "Shower grab bar",
    accessibility10: "Toilet grab bar",
    "": "Shower or bath chair",
  },
  {
    id: "33",
    name: "Big Group -> for 30 people with Chef",
    description:
      "Santuario Bacalar is a virgin untouched land  with all the comforts energized by solar power in the middle of the jungle. Enjoy our Chef's delicious cooking Hear the birds , feel the breeze, bathe in the lukewarm freshwater lagoon. Do yoga in lagoon front palapa. Roam the 45 hectare land visit the  lemon and coconut plantation. Care for the chickens.  Use kayaks and paddleboard to get to the other side of the lagoon. Paddle to the Boca. Picture yourself in the bluest hue in this world!",
    host: "Luis",
    number_bedrooms: "8",
    number_bathrooms: "7.5",
    number_beds: "16",
    address: "unsure",
    price: "2845",
    cleaning_price: "125",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Mexico",
    Region2: "North America",
    country: "Mexico",
    state: "Quintana Roo",
    city_id: "Bacalar",
    category: "Treehouses",
    extra_benefits1: "Self check-in",
    extra_benefits_description: "Check yourself in with the lockbox.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Pets allowed",
    amenity4: "Free parking on premises",
    amenity5: "Washer",
    amenity6: "Dryer",
    amenity7: "",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "34",
    name: "New! 8 BR Resort-Style Home, 3 min from the beach!",
    description:
      "You will love our 8 bedroom resort-style home...your very own deluxe private resort. We are very close to the beach and Uvita town (3 minutes), yet extremely private. Relax in our jungle pool, strike a pose on our panoramic ocean view yoga deck, hang out in a hammock and watch the toucans and monkeys, create your culinary masterpiece in our well-appointed kitchen and professional outdoor grilling area, or watch a movie in the jungle.",
    host: "Jeff",
    number_bedrooms: "8",
    number_bathrooms: "8.5",
    number_beds: "13",
    address: "unsure",
    price: "719",
    cleaning_price: "150",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Spanish",
    Region1: "Central America",
    Region2: "",
    country: "Costa Rica",
    state: "Provincia de Puntarenas",
    city_id: "Uvita",
    category: "Treehouses",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Private pool",
    amenity4: "Free parking on premises",
    amenity5: "TV",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "35",
    name: "Granai del Carmine - priv. pool and garden",
    description:
      "I Granai del Carmine is a delightful stone villa with swimming pool, located in the countryside of Conversano, it can comfortably accommodate up to 8 people. Ideal location for relaxing holidays, just a few kilometers from Conversano, Polignano a Mare, the sand beaches of Monopoli, the caves of Castellana Grotte and the wonderful Valle d'Itria.",
    host: "Alfredo",
    number_bedrooms: "4",
    number_bathrooms: "3",
    number_beds: "6",
    address: "unsure",
    price: "217",
    cleaning_price: "152",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "Puglia",
    city_id: "Conversano",
    category: "Historical homes",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A common area with wifi that's well-suited for working. ",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Dedicated workspace",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "Private pool",
    amenity7: "TV",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "36",
    name: "Intera villa con piscina e spa prive’ in Umbria",
    description:
      "Peace and quiet combined with the magnificent view from this villa reign supreme !! With all the comforts that we always put at your disposal. Large indoor spaces to be used in winter and summer sauna turkish bath and whirlpool will always be at your disposal as the use of the living room with a giant fireplace, cable TV or billiards will accompany the coldest days.",
    host: "Iolanda",
    number_bedrooms: "7",
    number_bathrooms: "5",
    number_beds: "10",
    address: "unsure",
    price: "585",
    cleaning_price: "217",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "Italian",
    Region1: "Italy",
    Region2: "Europe",
    country: "Italy",
    state: "Umbria",
    city_id: "Amelia",
    category: "Historical homes",
    extra_benefits1: "Dedicated workspace",
    extra_benefits_description:
      "A common area with wifi that's well-suited for working. ",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "Free cancellation for 48 hours",
    extra_benefits3_description: "",
    amenity1: "Mountain view",
    amenity2: "Wifi",
    amenity3: "Kitchen",
    amenity4: "Dedicated workspace",
    amenity5: "Free parking on premises",
    amenity6: "Private pool",
    amenity7: "Pets allowed",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "37",
    name: "Spectacular Views • Stunning Modern Broadmoor Home",
    description:
      "Our gorgeous custom home offers truly one of the best views in Colorado Springs from the comfort of a well-designed, contemporary space. Feel a world apart, immersed in nature, yet just a mile from the famous, world-renowned Broadmoor and 10 minutes from downtown.  ",
    host: "Ryan",
    number_bedrooms: "6",
    number_bathrooms: "4",
    number_beds: "10",
    address: "unsure",
    price: "880",
    cleaning_price: "300",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "North America",
    Region2: "",
    country: "United States",
    state: "Colorado",
    city_id: "Colorado Springs",
    category: "Golfing",
    extra_benefits1: "Free cancellation for 48 hours",
    extra_benefits_description: "",
    extra_benefits2: "",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Mountain view",
    amenity2: "Kitchen",
    amenity3: "Dedicated workspace",
    amenity4: "Wifi",
    amenity5: "Free parking on premises",
    amenity6: "TV",
    amenity7: "Washer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "38",
    name: "Wow High End Masterpiece Home",
    description:
      "5200 sqft Home is in The Highlands of Breckenridge.  Summer golf is on your doorstep. Mountain ski is 3 miles away. Sleeps 16. Amazing mountain views, Gourmet kitchen, stainless appliances. Movie room, pool table, ping pong, jaccuzi.Guest quarters. Pets are allowed.",
    host: "Amanda",
    number_bedrooms: "5",
    number_bathrooms: "6",
    number_beds: "8",
    address: "unsure",
    price: "1320",
    cleaning_price: "450",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "North America",
    Region2: "",
    country: "United States",
    state: "Colorado",
    city_id: "Breckenridge",
    category: "Golfing",
    extra_benefits1: "Self check-in",
    extra_benefits_description: "Check yourself in with the lockbox.",
    extra_benefits2: "Great location",
    extra_benefits2_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits3: "Free cancellation for 48 hours",
    extra_benefits3_description: "",
    amenity1: "Mountain view",
    amenity2: "Kitchen",
    amenity3: "Wifi",
    amenity4: "Free parking on premises",
    amenity5: "Pets allowed",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "TV",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "39",
    name: "5BD Modern A-Frame- Close to Ski Runs and Golfing",
    description: "",
    host: "Local",
    number_bedrooms: "5",
    number_bathrooms: "3.5",
    number_beds: "8",
    address: "unsure",
    price: "682",
    cleaning_price: "300",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "North America",
    Region2: "",
    country: "United States",
    state: "Colorado",
    city_id: "Victor",
    category: "Golfing",
    extra_benefits1: "Great location",
    extra_benefits_description:
      "100% of recent guests gave the location a 5-star rating.",
    extra_benefits2: "Free cancellation for 48 hours",
    extra_benefits2_description: "",
    extra_benefits3: "",
    extra_benefits3_description: "",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Free parking on premises",
    amenity4: "Washer",
    amenity5: "Dryer",
    amenity6: "TV",
    amenity7: "Hair dryer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
  {
    id: "40",
    name: "Luxury 5 BD/4.5 BR retreat at Teton foothills",
    description:
      "Beautifully furnished 4,500 sq ft home in the Teton Valley. Close to Grand Teton and Yellowstone National Parks, and surrounded by world-class mountain biking, hiking, fishing, golfing, and skiing (Grand Targhee and Jackson Hole). ",
    host: "Matt",
    number_bedrooms: "5",
    number_bathrooms: "4.5",
    number_beds: "6",
    address: "unsure",
    price: "450",
    cleaning_price: "300",
    property_type: "House",
    room_type: "Entire place",
    language1: "English",
    language2: "",
    Region1: "North America",
    Region2: "",
    country: "United States",
    state: "Idaho",
    city_id: "Grand Teton",
    category: "Golfing",
    extra_benefits1: "Superhost",
    extra_benefits_description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    extra_benefits2: "Self check-in",
    extra_benefits2_description: "Check yourself in with the lockbox.",
    extra_benefits3: "Great location",
    extra_benefits3_description:
      "100% of recent guests gave the check-in process a 5-star rating",
    amenity1: "Kitchen",
    amenity2: "Wifi",
    amenity3: "Free parking on premises",
    amenity4: "Pets allowed",
    amenity5: "TV",
    amenity6: "Washer",
    amenity7: "Dryer",
    amenity8: "",
    amenity9: "",
    amenity10: "",
    accessibility1: "",
    accessibility2: "",
    accessibility3: "",
    accessibility4: "",
    accessibility5: "",
    accessibility6: "",
    accessibility7: "",
    accessibility8: "",
    accessibility9: "",
    accessibility10: "",
    "": "",
  },
];

export default Json;
